name: Doxygen

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        fetch-depth: 0
    
    - name: Install Doxygen
      run: sudo apt install doxygen
      shell: bash

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --long --dirty=X)
      shell: bash

    - name: Configure CMake
      run: cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_DOC=ON

    - name: Build Doxygen docs
      run: cmake --build build -t doc

    - uses: actions/upload-artifact@v2
      name: Upload Artifact
      # Create a single artifact (zip folder) with binaries for 3 OSs
      with:
        name: mightex1304-${{steps.get_version.outputs.VERSION}}.doc
        path: |
          doc/html/*
    
